### ISSUE TITLE
onUnload函数内调用$goBack会导致连续关闭两个页面

### ISSUE THREAD

**Issue by jiujiuzhang99** [wendux/grace#13]
可以拦截吗？

**Comment by pyhpl** [comment]
你好，你解决了吗？我刚刚也遇到了这个问题

**Comment by jiujiuzhang99** [comment]
我挂emit来实现了

**Comment by pyhpl** [comment]
好的，谢谢

**Comment by wendux** [comment]
不应该在`onUnload`中再调用`$goBack`, 因为调用`onUnload`时，当前页面已经发生关闭，会回退到上一个页面，而 `$goBack`功能就是关闭页面回退到上一个页面，所以表现就是回退两次，正如 @jiujiuzhang99 所述，要在`onUnload`里回传数据的话，可以采用事件通知的方式。
