### ISSUE TITLE
http拦截器里promise不起作用

### ISSUE THREAD

**Issue by wfz90** [wendux/grace#16]
我的意思是如果访问接口a，a需要token，但是系统中没有token，需要访问接口b来获取，
我把检测token和接口b写在了 拦截器里，但是还没等到获取到token，a接口就已经开始响应了。

**Comment by wendux** [comment]
首先请更新工程，其次请参考 [fly拦截器](https://wendux.github.io/dist/#/doc/flyio/interceptor)中关于执行异步任务的部分。

**Comment by wfz90** [comment]
没有仔细看这个文档，谢谢

**Comment by wendux** [comment]
今天刚更新的
