### ISSUE TITLE
3个多月不维护，停止维护了吗？

### ISSUE THREAD

**Issue by lsw1990** [wendux/grace#25]
3个多月不维护，停止维护了吗？

**Comment by wendux** [comment]
@lsw1990 不会，近期比较忙，马上就会有一次fix.


--[From gitme Android](http://flutterchina.club)

**Comment by lsw1990** [comment]
期待马上到来

**Comment by ryanxin** [comment]
期待， fly 有一些bug 希望能merge上来

**Comment by wendux** [comment]
最新代码已提交，建议都更新一下

**Comment by lsw1990** [comment]
@wendux 更新了什么内容

**Comment by wendux** [comment]
bug修复及添加拦截器添加清空队列的clear方法
