### ISSUE TITLE
组件中data数据不变化

### ISSUE THREAD

**Issue by CurryHan** [wendux/grace#33]
1.page传入属性num,数值为1给组件
2.组件能拿到数值为1的num
3.page中num数值发生变化,+1变成2
4.组件中 <view>{{num}}</view> 也能显示成2,但是通过$this.data.num获取到值始终为1

提供小程序代码片段  wechatide://minicode/KKFRv3mP7e3r
@wendux 麻烦看下

**Comment by wendux** [comment]
用$this.$data.num取


 :octocat: [From gitme Android](http://flutterchina.club/app/gm.html)

**Comment by CurryHan** [comment]
是用的this.$data.num取的 上面写错了

**Comment by wendux** [comment]
属性的话用this.data.num取

**Comment by CurryHan** [comment]
好的
